### YamlMime:TSType
name: IDynamicDataSharedPropertyConfiguration
uid: '@microsoft/sp-property-pane!IDynamicDataSharedPropertyConfiguration:interface'
package: '@microsoft/sp-property-pane!'
fullName: IDynamicDataSharedPropertyConfiguration
summary: Configuration related to a shared property.
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: filters
    uid: '@microsoft/sp-property-pane!IDynamicDataSharedPropertyConfiguration#filters:member'
    package: '@microsoft/sp-property-pane!'
    fullName: filters
    summary: Filters for the shared property.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'filters?: IDynamicDataSharedPropertyFilters;'
      return:
        type: <xref uid="@microsoft/sp-property-pane!IDynamicDataSharedPropertyFilters:interface" />
