### YamlMime:TSTypeAlias
name: CardComponentConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: CardComponentConfiguration
summary: Base component configuration.
remarks: component configuration is the subset of component parameters that are available to a developer for customizations.
isPreview: false
isDeprecated: false
syntax: >-
  export declare type CardComponentConfiguration<T extends ICardComponentParameters = ICardComponentParameters, K
  extends keyof T | '' = ''> = Omit<T, K>;
