### YamlMime:TSTypeAlias
name: CardViewActionsFooterConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!CardViewActionsFooterConfiguration:type'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: CardViewActionsFooterConfiguration
summary: The actions-only footer configuration for the card view.
remarks: ''
example: []
isPreview: false
isDeprecated: false
syntax: >-
  export type CardViewActionsFooterConfiguration = ICardButtonConfiguration | [ICardButtonConfiguration,
  ICardButtonConfiguration] | undefined;
