### YamlMime:TSTypeAlias
name: GenericCardViewFooterConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!GenericCardViewFooterConfiguration:type'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: GenericCardViewFooterConfiguration
summary: The footer configuration for the Generic card view templates.
remarks: 'The Generic card view templates are Basic Card View, Primary Text Card View, and Image Card View.'
isPreview: true
isDeprecated: false
syntax: >-
  export declare type GenericCardViewFooterConfiguration = CardViewActionsFooterConfiguration |
  ICardTextInputConfiguration;
