### YamlMime:TSType
name: IBarChartCardViewConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!IBarChartCardViewConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: IBarChartCardViewConfiguration
summary: Configuration for a bar chart card view.
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: body
    uid: '@microsoft/sp-adaptive-card-extension-base!IBarChartCardViewConfiguration#body:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: body
    summary: Body area components.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        body: ICardBarChartConfiguration<T> | [ICardBarChartConfiguration<T>] | [ICardTextConfiguration,
        ICardBarChartConfiguration<T>];
      return:
        type: >-
          <xref uid="@microsoft/sp-adaptive-card-extension-base!ICardBarChartConfiguration:interface" />&lt;T&gt; |
          [<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardBarChartConfiguration:interface" />&lt;T&gt;] |
          [<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardTextConfiguration:interface" />, <xref
          uid="@microsoft/sp-adaptive-card-extension-base!ICardBarChartConfiguration:interface" />&lt;T&gt;]
extends: <xref uid="@microsoft/sp-adaptive-card-extension-base!IDataVisualizationCardViewConfiguration:interface" />
