### YamlMime:TSType
name: ICardBarChartConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardBarChartConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardBarChartConfiguration
summary: Configuration for a bar chart.
remarks: ''
isPreview: true
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardBarChartParameters:interface" />&lt;T&gt;&gt;
