### YamlMime:TSType
name: ICardPieChartConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardPieChartConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardPieChartConfiguration
summary: Configuration for a pie chart.
remarks: ''
isPreview: true
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardPieChartParameters:interface" />&gt;
