### YamlMime:TSType
name: ICardLineChartConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardLineChartConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardLineChartConfiguration
summary: Configuration for a line chart.
remarks: ''
example: []
isPreview: false
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardLineChartParameters:interface" />&lt;T&gt;&gt;
