### YamlMime:TSType
name: ICardViewConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardViewConfiguration
summary: Card view configuration
remarks: ''
isPreview: true
isDeprecated: false
type: interface
properties:
  - name: body
    uid: '@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration#body:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: body
    summary: Body area components.
    remarks: ''
    isPreview: true
    isDeprecated: false
    syntax:
      content: 'body: CardComponentConfiguration | CardComponentConfiguration[] | undefined;'
      return:
        type: >-
          <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" /> | <xref
          uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />[] | undefined
  - name: cardBar
    uid: '@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration#cardBar:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: cardBar
    summary: Card view title area (card bar) components.
    remarks: ''
    isPreview: true
    isDeprecated: false
    syntax:
      content: 'cardBar: ICardBarConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardBarConfiguration:interface" />'
  - name: footer
    uid: '@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration#footer:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: footer
    summary: Footer area components.
    remarks: ''
    isPreview: true
    isDeprecated: false
    syntax:
      content: 'footer: CardComponentConfiguration | CardComponentConfiguration[] | undefined;'
      return:
        type: >-
          <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" /> | <xref
          uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />[] | undefined
  - name: header
    uid: '@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration#header:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: header
    summary: Header area components.
    remarks: ''
    isPreview: true
    isDeprecated: false
    syntax:
      content: 'header: CardComponentConfiguration | CardComponentConfiguration[] | undefined;'
      return:
        type: >-
          <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" /> | <xref
          uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />[] | undefined
  - name: image
    uid: '@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration#image:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: image
    summary: Image displayed on the card.
    remarks: ''
    isPreview: true
    isDeprecated: false
    syntax:
      content: 'image: IAdaptiveCardExtensionImage | undefined;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!IAdaptiveCardExtensionImage:interface" /> | undefined'
