### YamlMime:TSType
name: ICardSearchFooterConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardSearchFooterConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardSearchFooterConfiguration
summary: Search box footer component configuration.
remarks: component configuration is the subset of component parameters that are available to a developer for customizations.
example: []
isPreview: false
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardSearchFooterParameters:interface" />&gt;
