### YamlMime:TSType
name: ICardTextInputConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardTextInputConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardTextInputConfiguration
summary: Text input component configuration.
remarks: component configuration is the subset of component parameters that are available to a developer for customizations.
example: []
isPreview: false
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardTextInputParameters:interface" />&gt;
