### YamlMime:TSType
name: ICardBarConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardBarConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardBarConfiguration
summary: Card view title area (card bar) component configuration.
remarks: component configuration is the subset of component parameters that are available to a developer for customizations.
example: []
isPreview: false
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardBarParameters:interface" />&gt;
