### YamlMime:TSType
name: ICardButtonConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ICardButtonConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ICardButtonConfiguration
summary: Card button component configuration.
remarks: component configuration is the subset of component parameters that are available to a developer for customizations.
example: []
isPreview: false
isDeprecated: false
type: interface
extends: >-
  <xref uid="@microsoft/sp-adaptive-card-extension-base!CardComponentConfiguration:type" />&lt;<xref
  uid="@microsoft/sp-adaptive-card-extension-base!ICardButtonParameters:interface" />&gt;
