### YamlMime:TSType
name: ISearchCardViewConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ISearchCardViewConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ISearchCardViewConfiguration
summary: Configuration for a Search Card view.
remarks: >-
  The Search Text Card view displays the following: - Card Title - Card Icon - One primary text field - One search box -
  Optional search box footer
example: []
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: body
    uid: '@microsoft/sp-adaptive-card-extension-base!ISearchCardViewConfiguration#body:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: body
    summary: Body area components.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'body: ICardSearchBoxConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardSearchBoxConfiguration:interface" />'
  - name: footer
    uid: '@microsoft/sp-adaptive-card-extension-base!ISearchCardViewConfiguration#footer:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: footer
    summary: Footer area components.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'footer: ICardSearchFooterConfiguration | undefined;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardSearchFooterConfiguration:interface" /> | undefined'
  - name: header
    uid: '@microsoft/sp-adaptive-card-extension-base!ISearchCardViewConfiguration#header:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: header
    summary: Header area components.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'header: ICardTextConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardTextConfiguration:interface" />'
extends: 'Omit&lt;<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration:interface" />, ''image''&gt;'
