### YamlMime:TSType
name: ITextInputImageCardViewConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputImageCardViewConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ITextInputImageCardViewConfiguration
summary: |-
  Configuration for an Text Input Card View

  \*
remarks: >-
  The Text Input Card view displays the following: - Card title - Card icon - One image - One primary text field - Zero
  text inputs in `Medium` Card size, one text input in `Large` Card size - Zero buttons in the `Medium` Card size, up to
  two buttons in `Large` Card size
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: body
    uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputImageCardViewConfiguration#body:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: body
    summary: Body area components.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'body: ICardTextInputConfiguration;'
      return:
        type: <xref uid="@microsoft/sp-adaptive-card-extension-base!ICardTextInputConfiguration:interface" />
  - name: footer
    uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputImageCardViewConfiguration#footer:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: footer
    summary: Footer area components.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'footer: CardViewActionsFooterConfiguration;'
      return:
        type: <xref uid="@microsoft/sp-adaptive-card-extension-base!CardViewActionsFooterConfiguration:type" />
  - name: header
    uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputImageCardViewConfiguration#header:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: header
    summary: Header area components.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'header: ICardTextConfiguration;'
      return:
        type: <xref uid="@microsoft/sp-adaptive-card-extension-base!ICardTextConfiguration:interface" />
  - name: image
    uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputImageCardViewConfiguration#image:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: image
    summary: Image displayed on the card.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'image: IAdaptiveCardExtensionImage;'
      return:
        type: <xref uid="@microsoft/sp-adaptive-card-extension-base!IAdaptiveCardExtensionImage:interface" />
extends: <xref uid="@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration:interface" />
