### YamlMime:TSType
name: ITextInputCardViewConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputCardViewConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ITextInputCardViewConfiguration
summary: |-
  Configuration for an Text Input Card View

  \*
remarks: >-
  The Text Input Card view displays the following: - Card title - Card icon - One primary text field - One text input -
  One buttons in the `Medium` Card size, up to two buttons in `Large` Card size
example: []
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: body
    uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputCardViewConfiguration#body:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: body
    summary: Body area components.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'body: ICardTextInputConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardTextInputConfiguration:interface" />'
  - name: footer
    uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputCardViewConfiguration#footer:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: footer
    summary: Footer area components.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'footer: CardViewActionsFooterConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!CardViewActionsFooterConfiguration:type" />'
  - name: header
    uid: '@microsoft/sp-adaptive-card-extension-base!ITextInputCardViewConfiguration#header:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: header
    summary: Header area components.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'header: ICardTextConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardTextConfiguration:interface" />'
extends: 'Omit&lt;<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration:interface" />, ''image''&gt;'
