### YamlMime:TSType
name: AadHttpClientConfiguration
uid: '@microsoft/sp-http-base!AadHttpClientConfiguration:class'
package: '@microsoft/sp-http-base!'
fullName: AadHttpClientConfiguration
summary: Configuration for HttpClient.
remarks: >-
  The HttpClientConfiguration object provides a set of switches for enabling/disabling various features of the
  HttpClient class. Normally these switches are set (e.g. when calling HttpClient.fetch()) by providing one of the
  predefined defaults from HttpClientConfigurations, however switches can also be changed via the
  HttpClientConfiguration.overrideWith() method.
example: []
isPreview: false
isDeprecated: false
type: class
constructors:
  - name: '(constructor)(flags, overrideFlags)'
    uid: '@microsoft/sp-http-base!AadHttpClientConfiguration:constructor(1)'
    package: '@microsoft/sp-http-base!'
    fullName: '(constructor)(flags, overrideFlags)'
    summary: >-
      Constructs a new instance of HttpClientConfiguration with the specified flags. The default values will be used for
      any flags that are missing or undefined. If overrideFlags is specified, it takes precedence over flags.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'constructor(flags: IAadHttpClientConfiguration, overrideFlags?: IAadHttpClientConfiguration);'
      parameters:
        - id: flags
          description: ''
          type: '<xref uid="@microsoft/sp-http-base!IAadHttpClientConfiguration:interface" />'
        - id: overrideFlags
          description: ''
          type: '<xref uid="@microsoft/sp-http-base!IAadHttpClientConfiguration:interface" />'
properties:
  - name: flags
    uid: '@microsoft/sp-http-base!AadHttpClientConfiguration#flags:member'
    package: '@microsoft/sp-http-base!'
    fullName: flags
    summary: ''
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'protected flags: IAadHttpClientConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-http-base!IAadHttpClientConfiguration:interface" />'
methods:
  - name: overrideWith(sourceFlags)
    uid: '@microsoft/sp-http-base!AadHttpClientConfiguration#overrideWith:member(1)'
    package: '@microsoft/sp-http-base!'
    fullName: overrideWith(sourceFlags)
    summary: ''
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: |-
        /** @override */
        overrideWith(sourceFlags: IAadHttpClientConfiguration): AadHttpClientConfiguration;
      parameters:
        - id: sourceFlags
          description: ''
          type: '<xref uid="@microsoft/sp-http-base!IAadHttpClientConfiguration:interface" />'
      return:
        type: '<xref uid="@microsoft/sp-http-base!AadHttpClientConfiguration:class" />'
        description: ''
extends: '<xref uid="@microsoft/sp-http-base!HttpClientConfiguration:class" />'
