### YamlMime:TSType
name: ISPHttpClientBatchConfiguration
uid: '@microsoft/sp-http-base!ISPHttpClientBatchConfiguration:interface'
package: '@microsoft/sp-http-base!'
fullName: ISPHttpClientBatchConfiguration
summary: Flags interface for SPHttpClientBatchConfiguration.
remarks: ''
isPreview: true
isDeprecated: false
type: interface
extends: <xref uid="@microsoft/sp-http-base!ISPHttpClientCommonConfiguration:interface" />
