### YamlMime:TSType
name: IODataFormsClientSideConfiguration
uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration:interface'
package: '@microsoft/sp-odata-types!'
fullName: IODataFormsClientSideConfiguration
summary: 'Represents a set of OData properties for objects that allow forms customizations (e.g. SP.List, SP.ContentType).'
remarks: ''
example: []
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: DislpayFormClientSideDisplayTarget
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DislpayFormClientSideDisplayTarget:member'
    package: '@microsoft/sp-odata-types!'
    fullName: DislpayFormClientSideDisplayTarget
    summary: 'Display Form display target (new tab, panel)'
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'DislpayFormClientSideDisplayTarget: string | undefined;'
      return:
        type: string | undefined
  - name: DisplayFormClientSideComponentId
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DisplayFormClientSideComponentId:member'
    package: '@microsoft/sp-odata-types!'
    fullName: DisplayFormClientSideComponentId
    summary: Display Form Customizer component id
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'DisplayFormClientSideComponentId: string | undefined;'
      return:
        type: string | undefined
  - name: DisplayFormClientSideComponentProperties
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#DisplayFormClientSideComponentProperties:member'
    package: '@microsoft/sp-odata-types!'
    fullName: DisplayFormClientSideComponentProperties
    summary: Display Form Customizer component properties
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'DisplayFormClientSideComponentProperties: string | undefined;'
      return:
        type: string | undefined
  - name: EditFormClientSideComponentId
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideComponentId:member'
    package: '@microsoft/sp-odata-types!'
    fullName: EditFormClientSideComponentId
    summary: Edit Form Customizer component id
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'EditFormClientSideComponentId: string | undefined;'
      return:
        type: string | undefined
  - name: EditFormClientSideComponentProperties
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideComponentProperties:member'
    package: '@microsoft/sp-odata-types!'
    fullName: EditFormClientSideComponentProperties
    summary: Edit Form Customizer component properties
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'EditFormClientSideComponentProperties: string | undefined;'
      return:
        type: string | undefined
  - name: EditFormClientSideDisplayTarget
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#EditFormClientSideDisplayTarget:member'
    package: '@microsoft/sp-odata-types!'
    fullName: EditFormClientSideDisplayTarget
    summary: 'Edit Form display target (new tab, panel)'
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'EditFormClientSideDisplayTarget: string | undefined;'
      return:
        type: string | undefined
  - name: NewFormClientSideComponentId
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideComponentId:member'
    package: '@microsoft/sp-odata-types!'
    fullName: NewFormClientSideComponentId
    summary: New Form Customizer component id
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'NewFormClientSideComponentId: string | undefined;'
      return:
        type: string | undefined
  - name: NewFormClientSideComponentProperties
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideComponentProperties:member'
    package: '@microsoft/sp-odata-types!'
    fullName: NewFormClientSideComponentProperties
    summary: New Form Customizer component properties
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'NewFormClientSideComponentProperties: string | undefined;'
      return:
        type: string | undefined
  - name: NewFormClientSideDisplayTarget
    uid: '@microsoft/sp-odata-types!IODataFormsClientSideConfiguration#NewFormClientSideDisplayTarget:member'
    package: '@microsoft/sp-odata-types!'
    fullName: NewFormClientSideDisplayTarget
    summary: 'New Form display target (new tab, panel)'
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'NewFormClientSideDisplayTarget: string | undefined;'
      return:
        type: string | undefined
