### YamlMime:TSPacakge
uid: '@microsoft/sp-application-base!'
name: '@microsoft/sp-application-base'
type: package
summary: >-
  SharePoint Framework support for building and extending client-side
  applications.
classes:
  - '@microsoft/sp-application-base!ApplicationAccessor:class'
  - '@microsoft/sp-application-base!ApplicationCustomizerContext:class'
  - '@microsoft/sp-application-base!BaseApplicationCustomizer:class'
  - '@microsoft/sp-application-base!PlaceholderContent:class'
  - '@microsoft/sp-application-base!PlaceholderProvider:class'
interfaces:
  - '@microsoft/sp-application-base!IPlaceholderCreateContentOptions:interface'
enums:
  - '@microsoft/sp-application-base!PlaceholderName:enum'
