### YamlMime:TSType
name: IDialogConfiguration
uid: '@microsoft/sp-dialog!IDialogConfiguration:interface'
package: '@microsoft/sp-dialog!'
fullName: IDialogConfiguration
summary: The interface for dialog configuration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: isBlocking
    uid: '@microsoft/sp-dialog!IDialogConfiguration#isBlocking:member'
    package: '@microsoft/sp-dialog!'
    fullName: isBlocking
    summary: >-
      Whether the dialog can be closed by clicking outside the dialog (on the
      overlay).
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'isBlocking?: boolean;'
      return:
        type: boolean
