### YamlMime:TSTypeAlias
name: IModuleConfiguration
uid: '@microsoft/sp-module-interfaces!IModuleConfiguration:type'
package: '@microsoft/sp-module-interfaces!'
fullName: IModuleConfiguration
summary: ''
remarks: ''
example: []
isPreview: true
isDeprecated: false
syntax: >-
  export declare type IModuleConfiguration = IComponentModuleConfiguration | IPathModuleConfiguration |
  ILocalizedPathModuleConfiguration;
