### YamlMime:TSType
name: IDynamicDataSharedSourceConfiguration
uid: '@microsoft/sp-webpart-base!IDynamicDataSharedSourceConfiguration:interface'
package: '@microsoft/sp-webpart-base!'
fullName: IDynamicDataSharedSourceConfiguration
summary: Configuration related to a shared source.
remarks: ''
isPreview: false
isDeprecated: true
customDeprecatedMessage: >-
  This is obsolete now. This interface has been moved to
  `@microsoft/sp-property-pane`<!-- -->. Please consume it from there.
type: interface
extends: >-
  <xref
  uid="@microsoft/sp-webpart-base!IDynamicDataSharedSourceConfiguration~0:complex"
  />
