### YamlMime:TSType
name: IPropertyPaneConfiguration
uid: '@microsoft/sp-webpart-base!IPropertyPaneConfiguration:interface'
package: '@microsoft/sp-webpart-base!'
fullName: IPropertyPaneConfiguration
summary: Web part configuration settings
remarks: We have left the original implementation here to avoid breaking the public API contract.
isPreview: false
isDeprecated: true
customDeprecatedMessage: >-
  This is obsolete now. This interface has been moved to `@microsoft/sp-property-pane`<!-- -->. Please consume it from
  there.
type: interface
extends: <xref uid="@microsoft/sp-property-pane!IPropertyPaneConfiguration:interface" />
