### YamlMime:TSTypeAlias
name: ThrottleSettings
uid: '@microsoft/sp-lodash-subset!ThrottleSettings:type'
package: '@microsoft/sp-lodash-subset!'
fullName: ThrottleSettings
summary: ''
remarks: ''
example: []
isPreview: false
isDeprecated: false
syntax: export declare type ThrottleSettings = ThrottleSettings2;
