### YamlMime:TSType
name: ApplicationCustomizerContext
uid: '@microsoft/sp-application-base!ApplicationCustomizerContext:class'
package: '@microsoft/sp-application-base!'
fullName: ApplicationCustomizerContext
summary: >-
  The component context for
  [BaseApplicationCustomizer](xref:@microsoft/sp-application-base!BaseApplicationCustomizer:class)<!-- -->.
remarks: >-
  The constructor for this class is marked as internal. Third-party code should not call the constructor directly or
  create subclasses that extend the `ApplicationCustomizerContext` class.
isPreview: false
isDeprecated: false
type: class
properties:
  - name: application
    uid: '@microsoft/sp-application-base!ApplicationCustomizerContext#application:member'
    package: '@microsoft/sp-application-base!'
    fullName: application
    summary: Provides access to the client-side application that is currently running.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'get application(): ApplicationAccessor;'
      return:
        type: '<xref uid="@microsoft/sp-application-base!default:class" />'
  - name: placeholderProvider
    uid: '@microsoft/sp-application-base!ApplicationCustomizerContext#placeholderProvider:member'
    package: '@microsoft/sp-application-base!'
    fullName: placeholderProvider
    summary: Exposes a collection of content placeholders for use by third parties.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'get placeholderProvider(): PlaceholderProvider;'
      return:
        type: '<xref uid="@microsoft/sp-application-base!default:class" />'
methods:
  - name: dispose()
    uid: '@microsoft/sp-application-base!ApplicationCustomizerContext#dispose:member(1)'
    package: '@microsoft/sp-application-base!'
    fullName: dispose()
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: |-
        /** @override */
        dispose(): void;
      return:
        type: void
        description: ''
extends: '<xref uid="@microsoft/sp-extension-base!ExtensionContext:class" />'
