### YamlMime:TSType
name: HttpClientConfiguration
uid: '@microsoft/sp-http!HttpClientConfiguration:class'
package: '@microsoft/sp-http!'
fullName: HttpClientConfiguration
summary: Configuration for HttpClient.
remarks: >-
  The HttpClientConfiguration object provides a set of switches for enabling/disabling various features of the
  HttpClient class. Normally these switches are set (e.g. when calling HttpClient.fetch()) by providing one of the
  predefined defaults from HttpClientConfigurations, however switches can also be changed via the
  HttpClientConfiguration.overrideWith() method.
example: []
isPreview: false
isDeprecated: false
type: class
constructors:
  - name: '(constructor)(flags, overrideFlags)'
    uid: '@microsoft/sp-http!HttpClientConfiguration:constructor(1)'
    package: '@microsoft/sp-http!'
    fullName: '(constructor)(flags, overrideFlags)'
    summary: >-
      Constructs a new instance of HttpClientConfiguration with the specified flags. The default values will be used for
      any flags that are missing or undefined. If overrideFlags is specified, it takes precedence over flags.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'constructor(flags: IHttpClientConfiguration, overrideFlags?: IHttpClientConfiguration);'
      parameters:
        - id: flags
          description: ''
          type: '<xref uid="@microsoft/sp-http!IHttpClientConfiguration:interface" />'
        - id: overrideFlags
          description: ''
          type: '<xref uid="@microsoft/sp-http!IHttpClientConfiguration:interface" />'
properties:
  - name: flags
    uid: '@microsoft/sp-http!HttpClientConfiguration#flags:member'
    package: '@microsoft/sp-http!'
    fullName: flags
    summary: ''
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'protected flags: IHttpClientConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-http!IHttpClientConfiguration:interface" />'
methods:
  - name: initializeFlags()
    uid: '@microsoft/sp-http!HttpClientConfiguration#initializeFlags:member(1)'
    package: '@microsoft/sp-http!'
    fullName: initializeFlags()
    summary: Child classes should override this method to initialize the flags object.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: |-
        /** @virtual */
        protected initializeFlags(): void;
      return:
        type: void
        description: ''
  - name: overrideWith(sourceFlags)
    uid: '@microsoft/sp-http!HttpClientConfiguration#overrideWith:member(1)'
    package: '@microsoft/sp-http!'
    fullName: overrideWith(sourceFlags)
    summary: 'Child classes should override this method to construct the child class type, rather than the base class type.'
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: |-
        /** @virtual */
        overrideWith(sourceFlags: IHttpClientConfiguration): HttpClientConfiguration;
      parameters:
        - id: sourceFlags
          description: ''
          type: '<xref uid="@microsoft/sp-http!IHttpClientConfiguration:interface" />'
      return:
        type: '<xref uid="@microsoft/sp-http!default:class" />'
        description: ''
