### YamlMime:TSType
name: IHttpClientConfigurations
uid: '@microsoft/sp-http!IHttpClientConfigurations:interface'
package: '@microsoft/sp-http!'
fullName: IHttpClientConfigurations
summary: Standard configurations for HttpClient.
remarks: >-
  This interface provides standard predefined HttpClientConfiguration objects for use with the HttpClient class. In
  general, clients should choose the latest available version number, which enables all the switches that are
  recommended for typical scenarios. (If new switches are introduced in the future, a new version number will be
  introduced, which ensures that existing code will continue to function the way it did at the time when it was tested.)
example: []
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: v1
    uid: '@microsoft/sp-http!IHttpClientConfigurations#v1:member'
    package: '@microsoft/sp-http!'
    fullName: v1
    summary: >-
      This configuration turns off every feature switch for HttpClient. The fetch() behavior will be essentially
      identical to the WHATWG standard API that is documented here: https://fetch.spec.whatwg.org/
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'readonly v1: HttpClientConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-http!default:class" />'
