### YamlMime:TSType
name: ISPHttpClientCommonConfiguration
uid: '@microsoft/sp-http!ISPHttpClientCommonConfiguration:interface'
package: '@microsoft/sp-http!'
fullName: ISPHttpClientCommonConfiguration
summary: Flags interface for SPHttpClientCommonConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: jsonRequest
    uid: '@microsoft/sp-http!ISPHttpClientCommonConfiguration#jsonRequest:member'
    package: '@microsoft/sp-http!'
    fullName: jsonRequest
    summary: Automatically configure the "Content-Type" header for a JSON payload.
    remarks: >-
      When this switch is true:


      If the "Content-Type" header was not explicitly added for the request,
      then SPHttpClient will add it if the request is a write operation (i.e. an
      HTTP method other than "GET", "HEAD", or "OPTIONS").


      For OData 3.0, the value is
      'application/json;odata=verbose;charset=utf-8'.


      For OData 4.0, the value is 'application/json;charset=utf-8'.
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'jsonRequest?: boolean;'
      return:
        type: boolean
  - name: jsonResponse
    uid: '@microsoft/sp-http!ISPHttpClientCommonConfiguration#jsonResponse:member'
    package: '@microsoft/sp-http!'
    fullName: jsonResponse
    summary: Automatically configure the "Accept" header for a JSON payload.
    remarks: >-
      When this switch is true:


      If the "Accept" header was not explicitly added for the request, then
      SPHttpClient will add it.


      For OData 3.0, the value is 'application/json'.


      For OData 4.0, the value is 'application/json;odata.metadata=minimal'.
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'jsonResponse?: boolean;'
      return:
        type: boolean
extends: '<xref uid="@microsoft/sp-http!IHttpClientConfiguration:interface" />'
