### YamlMime:UniversalReference
items:
  - uid: sp-http.ISPHttpClientBatchConfigurations
    summary: Standard configurations for SPHttpClient.
    remarks: >-
      This interface provides standard predefined SPHttpClientBatchConfiguration objects for use with the
      SPHttpClientBatch class. In general, clients should choose the latest available version number, which enables all
      the switches that are recommended for typical scenarios. (If new switches are introduced in the future, a new
      version number will be introduced, which ensures that existing code will continue to function the way it did at
      the time when it was tested.)
    isPreview: true
    name: ISPHttpClientBatchConfigurations
    fullName: ISPHttpClientBatchConfigurations
    langs:
      - typeScript
    type: interface
    package: sp-http
    children:
      - sp-http.ISPHttpClientBatchConfigurations.v1
  - uid: sp-http.ISPHttpClientBatchConfigurations.v1
    summary: 'Version 1 enables these switches: consoleLogging = true; jsonRequest = true; jsonResponse = true'
    isPreview: true
    name: v1
    fullName: v1
    langs:
      - typeScript
    type: property
    syntax:
      content: 'readonly v1: SPHttpClientBatchConfiguration;'
      return:
        type:
          - sp-http.SPHttpClientBatchConfiguration
